namespace EnumUtilitiesGenerator
{
    internal class Constants
    {
        public const string GENERATEHELPER_FULL_NAME = "EnumUtilitiesGenerator.Attributes.GenerateHelperAttribute";

        public const string GENERATEHELPER_ATTRIBUTE = @"// <auto-generated />

using System;

namespace EnumUtilitiesGenerator.Attributes
{
    [AttributeUsage(AttributeTargets.Enum, AllowMultiple = false, Inherited = false)]
    public sealed class GenerateHelperAttribute : Attribute
    {
        public GenerateHelperAttribute(GenerateExtensionOption generationOption)
        {
            GenerationOption = generationOption;
        }

        public GenerateExtensionOption GenerationOption { get; }
    }

    public enum GenerateExtensionOption
    {
        IgnoreEnumWithoutDescription = 1,
        ThrowForEnumWithoutDescription = 2,
        UseItselfWhenNoDescription = 3
    }
}";

        public const string NAMESPACE_TEMPLATE = @"// <auto-generated />

namespace {namespaceValue}
{
{classTemplate}
}";

        public const string CLASS_TEMPLATE = @"    public static class {enumName}Helper
    {
{methodTemplate}
    }";

    }
}
