namespace EnumUtilitiesGenerator
{
    internal class Constants
    {
        public const string GENERATEHELPER_FULL_NAME = "GenerateHelperAttribute";

        public const string GENERATEHELPER_ATTRIBUTE = @"// <auto-generated />
using System;

[AttributeUsage(AttributeTargets.Enum, AllowMultiple = false, Inherited = false)]
public sealed class GenerateHelperAttribute : Attribute
{
    public GenerateHelperAttribute(GenerateHelperOption generationOption)
    {
        GenerationOption = generationOption;
    }

    public GenerateHelperOption GenerationOption { get; }
}

public enum GenerateHelperOption
{
    IgnoreEnumWithoutDescription = 1,
    ThrowForEnumWithoutDescription = 2,
    UseItselfWhenNoDescription = 3
}";

        public const string NAMESPACE_TEMPLATE = @"// <auto-generated />
using System;

namespace {namespaceValue}
{
{classTemplate}
}";

        public const string CLASS_TEMPLATE = @"    public static class {enumName}Helper
    {
{methodTemplate}
    }";

    }
}
